default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: alex
  password: 'qwer'

development:
  <<: *default
  database: facemash_development

test:
  <<: *default
  database: facemash_test